# Generated by Django 4.2.1 on 2023-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
